# NOMBRE : Nelson Sanabio Maldonado
# Respuesta2-a : El código muestra en encontrar los índices de la primera fila de la matrix X
```{r}
A <- c(1,2,NA,6,7,8,4,6,7,8,NA,3,4,7,NA,10)
A <- matrix(A,nrow=4,ncol=4,byrow = T)
which(A[1,]!=is.integer(NA))

```
#Respuesta2-b : Respondiendo las preguntas de vectorización y reciclado 

```{r}

#VECTORIZACION
#Se dice que una función es vectorizada si acepta un array o vector(puede incluir un numero porque este es de una dimensión unitaria) como parametro de la función creada
Vectorizacion <- function(x){
  x*x #esta operación multiplica el vector x consigo misma
}
#Ejemplos
Vectorizacion(3) 
Vectorizacion(c(2,4,6,8))

#RECICLAJE
#Se dice que una función es reciclado cuando tiene 2 o más parametros de distinta longitud en lo cual hace operaciones y todas las variables cumplen dicha operación es decir si un vector es de longitud 10, los demas se acoplaran a este vector , repitiendo sus valores para llegar a la longitud 10

reciclaje <- function(x,y,z){
	x * y * z # imprime la multiplicación de los vectores x y z de cada elemento
}
#Ejemplos
#x = 1 3 5 7 9
#y = 3 7 8 3 7
#z = 2 2 2 2 2
x <- seq(1,10,2)
y <- c(3,7,8)
z <- 2
reciclaje(x,y,z) 



```
